#!/hint/bash

# C/C++编译参数
CFLAGS="-march=x86-64-v3 -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="${CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"

# 链接参数
LDFLAGS="-Wl,-O4,--sort-common,--as-needed,-z,relro,-z,now"

# Rust编译参数
RUSTFLAGS="-C opt-level=3"

# make命令参数
MAKEFLAGS="-j$(nproc) --quiet"

# 压缩参数
COMPRESSGZ=(gzip -c -f -n --best)
COMPRESSBZ2=(bzip2 -c -f --best)
COMPRESSXZ=(xz -T 0 -c -z --best -)
COMPRESSZST=(zstdmt -c -z -q -13 -)
COMPRESSLRZ=(lrzip -9 -q)
COMPRESSLZO=(lzop -q --best)
COMPRESSZ=(compress -c -f)
COMPRESSLZ4=(lz4 -q --best)
COMPRESSLZ=(lzip -c -f)
